{{- if .Values.gateway.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "arc-mcp.fullname" . }}
  labels:
    {{- include "arc-mcp.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "arc-mcp.selectorLabels" . | nindent 4 }}
{{- end }}
